# Generated by Django 3.0.2 on 2020-02-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trynkit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='file1',
            field=models.BinaryField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='file1name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='file2',
            field=models.BinaryField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='file2name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='file3',
            field=models.BinaryField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='file3name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='file4',
            field=models.BinaryField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='file4name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='file5',
            field=models.BinaryField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='file5name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
