# Generated by Django 3.0.3 on 2020-02-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trynkit', '0002_auto_20200128_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file1',
            field=models.BinaryField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='file1name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='file2',
            field=models.BinaryField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='file2name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='file3',
            field=models.BinaryField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='file3name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='file4',
            field=models.BinaryField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='file4name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='file5',
            field=models.BinaryField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='file5name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
