# Generated by Django 3.0.2 on 2020-02-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trynkit', '0002_auto_20200208_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Post',
        ),
    ]
