# Generated by Django 3.0.2 on 2020-02-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trynkit', '0003_auto_20200208_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='User',
        ),
    ]
