# Generated by Django 3.0.2 on 2020-02-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trynkit', '0004_auto_20200208_2018'),
        ('Trynkit', '0002_auto_20200128_2215'),
    ]

    operations = [
    ]
